// All persistent gameplay values use native flag containers.
local A = ::AfeiExpedition;
A.Flags <- {NamedId="afei_named_id",CaptainAfei="afei_captain_afei",Camped="afei_camped",ProxyCaptain="afei_proxy_captain",GrowthDone="afei_growth_done_",WinCount="afei_win_count",AfeiDead="afei_captain_dead",AfeiAwakened="afei_awakened",JiahaoCount="afei_jiahao_count",CampEnabled="afei_camp_enabled",SafeDeliveryHome="afei_safe_delivery_home"};
foreach(i in [1,2,3,4,5,6,7,8,9]) A.Flags["M0"+i+"Done"] <- "afei_m0"+i+"_done";
A.w <- function(k,fallback=0) { return ::World.Flags.has("afei_"+k)?::World.Flags.get("afei_"+k):fallback; };
A.sw <- function(k,v) { ::World.Flags.set("afei_"+k,v); return v; };
A.inc <- function(k,n=1) { return this.sw(k,this.w(k)+n); };
A.g <- function(a,k,fallback=0) { return a.getFlags().has("afei_"+k)?a.getFlags().get("afei_"+k):fallback; };
A.s <- function(a,k,v) { a.getFlags().set("afei_"+k,v); return v; };
A.bump <- function(a,k,n=1) { return this.s(a,k,this.g(a,k)+n); };
A.cid <- function(a) { return a==null?"":this.g(a,"named_id",""); };
A.grown <- function(a) { return this.w("growth_done_"+this.cid(a),false)!=false; };
A.roster <- function() { return ::World.getPlayerRoster().getAll(); };
A.named <- function(id,active=false) { foreach(a in this.roster()) if(this.cid(a)==id && (!active || !this.g(a,"camped"))) return a; return null; };
A.hasNamed <- function(id) { return this.named(id)!=null; };
A.isAfeiOrigin <- function() { return "World" in getroottable() && ::World.Assets!=null && ::World.Assets.getOrigin()!=null && ::World.Assets.getOrigin().getID()=="scenario.afei_expedition"; };
A.now <- function() { return ::Time.getVirtualTimeF(); };
A.hours <- function(n) { return n*::World.getTime().SecondsPerDay/24.0; };
A.day <- function() { return ::World.getTime().Days; };
A.round <- function() { return ::Time.getRound(); };
A.getRound <- function() { return this.round(); };
A.id <- function(a) { return a==null?0:a.getID(); };
A.findActor <- function(id) { if(!id) return null; local a=::Tactical.getEntityByID(id); return a!=null && a.isAlive()?a:null; };
A.actors <- function() { return ::Tactical.Entities.getInstancesOfFaction(::Const.Faction.Player); };
A.ready <- function(a) { return a!=null && a.isAlive() && !a.isDying() && a.getMoraleState()!=::Const.MoraleState.Fleeing && !a.getCurrentProperties().IsStunned && !a.getSkills().hasSkill("effects.sleeping") && !a.getSkills().hasSkill("effects.charmed"); };
A.player <- function(a) { return a!=null && a.isPlayerControlled() && !a.isGuest(); };
A.distance <- function(a,b) { return a.getTile().getDistanceTo(b.getTile()); };
A.allies <- function(a,r,other=true) { local ret=[]; foreach(b in this.actors()) if(this.player(b) && this.ready(b) && (!other || b.getID()!=a.getID()) && this.distance(a,b)<=r) ret.push(b); return ret; };
A.enemies <- function(a,r=1) { local ret=[]; foreach(group in ::Tactical.Entities.getAllInstances()) foreach(b in group) if(b!=null && b.isAlive() && !b.isAlliedWith(a) && this.distance(a,b)<=r) ret.push(b); return ret; };
A.shield <- function(a) { local i=a.getItems().getItemAtSlot(::Const.ItemSlot.Offhand); return i!=null && i.isItemType(::Const.Items.ItemType.Shield); };
A.weapon <- function(a) { return a.getItems().getItemAtSlot(::Const.ItemSlot.Mainhand); };
A.weaponType <- function(a,t) { local i=this.weapon(a); return i!=null && i.isWeaponType(t); };
A.has <- function(a,id) { return a!=null && a.getSkills().hasSkill("actives.afei_"+id); };
A.isHumanlike <- function(a,green=true) {if(a==null || !a.isAlive())return false;if(::isKindOf(a,"human"))return true;if(!green)return false;local t=a.getType();foreach(k in ["OrcYoung","OrcWarrior","OrcBerserker","OrcWarlord","GoblinFighter","GoblinAmbusher","GoblinLeader","GoblinShaman"])if(k in ::Const.EntityType && t==::Const.EntityType[k])return true;return false;};
A.mentalTarget <- function(a,green=true) {return this.isHumanlike(a,green) && !a.getCurrentProperties().IsImmuneToFearAndPanic;};
A.humanoid <- function(a) {return this.isHumanlike(a) && !a.getCurrentProperties().IsImmuneToKnockBackAndGrab;};
A.unique <- function(a,key,value) { local k=key+"_seen_"+value; if(this.g(a,k)) return false; this.s(a,k,true); this.bump(a,key); return true; };
A.getPaidContracts <- function() { return this.w("paid_contracts"); };
A.countNamedInRoster <- function() { local n=0; foreach(a in this.roster()) if(this.cid(a)!="") ++n; return n; };
A.countNamedEverRecruited <- function() { local n=0; foreach(id,d in this.Characters) if(this.w("ever_"+id)) ++n; return n; };
A.getJiahaoCount <- function() { return this.w("jiahao_count"); };
A.markEverRecruited <- function(id) { this.sw("ever_"+id,true); };
A.battleKey <- function() { return this.w("battle_id"); };
A.battleG <- function(a,k,def=0) { return this.g(a,"b"+this.battleKey()+"_"+k,def); };
A.battleS <- function(a,k,v) { return this.s(a,"b"+this.battleKey()+"_"+k,v); };
A.battleInc <- function(a,k,n=1) { return this.battleS(a,k,this.battleG(a,k)+n); };
A.once <- function(a,k) { if(this.battleG(a,k+"_round",-1)==this.round()) return false; this.battleS(a,k+"_round",this.round()); return true; };
A.seenThisRound <- function(a,k) { return this.battleG(a,k+"_round",-1)==this.round(); };
A.recover <- function(a,n) { if(!this.ready(a)) return 0; local key="recovery_"+this.round(); local take=::Math.min(::Math.min(n,a.getFatigue()),::Math.max(0,20-this.battleG(a,key))); if(take>0) { a.setFatigue(a.getFatigue()-take); this.battleInc(a,key,take); }
 return take; };
A.center <- function() { local c=this.named("C01"); if(c!=null && this.battleG(c,"deployed") && this.ready(c)) return c; local p=this.findActor(this.w("battle_proxy")); return this.ready(p)?p:null; };
A.note <- function(t) { ::logInfo("[Afei] "+t); this.sw("last_notice",t); };
