local checks=0,origin=true,actors=[],stashItems=[];
local tactical=false,combatStart=0;
local check=function(ok,label){if(!ok)throw "FAIL "+label;checks++;};
::Const <- {ItemSlot={Mainhand=0}};
::AfeixExpedition <- {isOrigin=function(){return origin;},roster=function(){return actors;}};
dofile("src/scripts/mods/afeix/core.nut");
::AfeixExpedition.isOrigin = function(){return origin;};
::AfeixExpedition.roster = function(){return actors;};
::Tactical <- {isActive=function(){return tactical;}};
::Math <- {min=function(a,b){return a<b?a:b;}};
local hooks={};
::mods_hookNewObject <- function(path,cb){hooks[path]<-cb;};
::mods_hookExactClass <- function(path,cb){hooks[path]<-cb;};
::doesBrushExist <- function(name){return true;};
dofile("src/scripts/mods/afeix/banner_hooks.nut");
::inherit <- function(path,body){return body;};
dofile(".cache/afei-art/native-contract-fixture/player_banner.nut");
local sprite=function(name){return {brush=name,Visible=false,Alpha=123,setBrush=function(v){this.brush=v;},resetBrush=function(){this.brush=null;}};};
local sprites={banner=sprite("banner_15"),zoom_banner=sprite("banner_15"),body=sprite("camp")};
local party={hasSprite=function(n){return n in sprites;},getSprite=function(n){return sprites[n];}};
local assets={m={Banner="banner_15",BannerID=15},getBanner=function(){return this.m.Banner;},
    getStash=function(){return {getItems=function(){return stashItems;}};}};
hooks["states/world/asset_manager"](assets);
local savedFlags={};
::World <- {Assets=assets,State={getPlayer=function(){return party;},getCombatStartTime=function(){return combatStart;}},
    Flags={has=function(k){return k in savedFlags;},get=function(k){return savedFlags[k];},set=function(k,v){savedFlags[k]<-v;}}};
check(assets.getBanner()=="banner_15"&&assets.m.BannerID==15,"unconfigured campaign retains founding choice");
savedFlags.afeix_banner_style <- "classic";
local parts={background=sprite("old"),shaft=sprite("old")};
local actor={added=0,dirty=0,getID=function(){return 1;},hasSprite=function(n){return n in parts;},getSprite=function(n){return parts[n];},setDirty=function(v){this.dirty++;}};
local weapon=clone ::player_banner;weapon.m={Variant=15,Icon="",IconLarge="",RegularDamage=50,RegularDamageMax=70};
weapon.setdelegate(getroottable());weapon.weapon<-{onEquip=function(){},onUnequip=function(){}};
weapon.getContainer<-function(){return {getActor=function(){return actor;}};};
weapon.new<-function(path){return {m={Icon="",IconDisabled="",Overlay=""}};};
weapon.addSkill<-function(s){actor.added++;};weapon.getID<-function(){return "weapon.player_banner";};
hooks["items/tools/player_banner"](weapon);
actor.getItems<-function(){return {getAllItems=function(){return [weapon];},getItemAtSlot=function(slot){return weapon;}};};
actors=[actor];
weapon.updateVariant();weapon.onEquip();
check(weapon.m.Icon=="weapons/afeix_toad_banner_70x70.png"&&parts.background.brush=="afeix_toad_standard","native standard gets custom inventory and held art");
check(actor.added==1&&weapon.m.RegularDamage==50&&weapon.m.RegularDamageMax==70&&weapon.m.Variant==15,"native skill damage and saved variant retained");
local world={onDeserialize=function(input){origin=true;parts.background.brush="native-loaded";return 42;}};
hooks["states/world_state"](world);
check(world.onDeserialize(null)==42&&sprites.banner.brush=="banner_afeix_toad"&&sprites.zoom_banner.brush=="banner_afeix_toad","old world save refreshes both map flags after origin load");
check(parts.background.brush=="afeix_toad_standard"&&actor.added==1,"held saved standard refreshes without adding skills twice");
check(!sprites.banner.Visible&&sprites.zoom_banner.Alpha==123&&sprites.body.brush=="camp","camp visibility zoom fade and map figure preserved");
weapon.onUnequip();check(parts.background.brush==null&&parts.shaft.brush==null,"native unequip removes custom art");
origin=false;weapon.updateVariant();weapon.onEquip();
check(assets.getBanner()=="banner_15"&&weapon.m.Icon=="weapons/banner/banner_15_70x70.png"&&parts.background.brush=="player_banner_15","other origin stays native");
sprites.banner.brush="another-origin";::AfeixExpedition.syncToadBanner();
check(sprites.banner.brush=="another-origin","world sync excludes other origins");
origin=true;
local A=::AfeixExpedition;
dofile("src/scripts/mods/afeix/ledger.nut");
dofile("src/scripts/mods/afeix/dream_ledger.nut");
A.CombatMax <- 12;
A.deployedIds <- function(){return [];};
A.canManage = function(){return true;};
A.hasStoryRecords <- function(){return true;};
A.hasIdeaRecords <- function(){return true;};
A.trainingLedgerPage <- function(event,page){return null;};
local event={m={Notice=""}};
local home=A.ledgerPage(event,"home");
check(home.Options.len()==6,"full home with dream and banner entry stays within six buttons");
check(home.Options[3].getResult(event)=="company","home exposes company submenu");
check(home.Options[4].getResult(event)=="dream_final","dream final stays directly accessible on home");
local company=A.ledgerPage(event,"company");
check(company.Options.len()==4&&company.Options[0].getResult(event)=="training"&&company.Options[1].getResult(event)=="banners","training and banner routes remain reachable");
check(company.Options[2].getResult(event)=="journey_index","history remains accessible within company affairs");
A.treatmentLedgerPage <- function(event,page){return null;};
A.toggleCompanyHelmets <- function(){return {ok=true,text=""};};
check(A.ledgerPage(event,"company").Options.len()==6,"company affairs including all services and history fits six buttons");
local choices=A.ledgerPage(event,"banners");
check(choices.Options.len()==6&&choices.Options[5].getResult(event)=="company","first four choices and navigation fit native event UI");
local spare=clone weapon;spare.m=clone weapon.m;stashItems=[null,spare];
local skillsBefore=actor.added;
check(choices.Options[4].getResult(event)=="banners:4","next page reaches remaining flags");
local secondPage=A.ledgerPage(event,"banners:4");
check(secondPage.Options.len()==4&&secondPage.Options[2].getResult(event)=="banners:0"&&secondPage.Options[3].getResult(event)=="company","second page fits and returns to both first page and company");
foreach (index,banner in A.ToadBanners) {
    local page=index<4?choices:secondPage, row=index<4?index:index-4;
    check(page.Options[row].getResult(event)==(index<4?"banners:0":"banners:4")&&savedFlags.afeix_banner_style==banner.key,"distinct option persists "+banner.key);
    if(banner.key=="native") {
        check(assets.getBanner()=="banner_15"&&sprites.banner.brush=="banner_15"&&sprites.zoom_banner.brush=="banner_15","restore exact founding map flag");
        check(parts.background.brush=="player_banner_15"&&parts.shaft.brush=="player_banner_15_shaft","restore native held flag and matching shaft");
        check(weapon.m.Icon=="weapons/banner/banner_15_70x70.png"&&spare.m.IconLarge=="weapons/banner/banner_15.png","restore native standard inventory icons");
        check(A.ledgerPage(event,"banners").Text.find("banner_15s.png")!=null,"native flag preview uses saved choice");
        continue;
    }
    check(assets.getBanner()=="banner_afeix_toad"+banner.suffix&&sprites.banner.brush==assets.getBanner()&&sprites.zoom_banner.brush==assets.getBanner(),"both map flags follow "+banner.key);
    check(parts.background.brush=="afeix_toad_standard"+banner.suffix&&parts.shaft.brush=="player_banner_15_shaft","held standard follows "+banner.key);
    check(weapon.m.Icon=="weapons/afeix_toad_banner"+banner.suffix+"_70x70.png"&&spare.m.IconLarge=="weapons/afeix_toad_banner"+banner.suffix+".png","held and stashed inventory icons follow "+banner.key);
    check(A.ledgerPage(event,"banners").Text.find("banner_afeix_toad"+banner.suffix+"s.png")!=null,"choice page previews "+banner.key);
}
check(actor.added==skillsBefore&&weapon.m.RegularDamage==50&&weapon.m.RegularDamageMax==70&&weapon.m.Variant==15,"repeated visual switches preserve native skills stats and variant");
check(!sprites.banner.Visible&&sprites.zoom_banner.Alpha==123&&sprites.body.brush=="camp","switching preserves camp and fade state");
local campaignSave=clone savedFlags;
savedFlags={};
check(A.toadBanner().key=="native","fresh campaign without flag uses founding banner");
savedFlags=clone campaignSave;
sprites.banner.brush="load-pending";spare.m.IconLarge="load-pending";
world.onDeserialize(null);
check(A.toadBanner().key=="golden"&&sprites.banner.brush=="banner_afeix_toad_golden"&&spare.m.IconLarge=="weapons/afeix_toad_banner_golden.png","load restores saved selection and stash visuals");
check(!A.chooseToadBanner("unknown").ok&&savedFlags.afeix_banner_style=="golden","invalid option cannot change saved selection");
tactical=true;
check(!A.chooseToadBanner("front").ok&&savedFlags.afeix_banner_style=="golden","combat blocks changing selection");
tactical=false;combatStart=1;
check(!A.chooseToadBanner("front").ok&&savedFlags.afeix_banner_style=="golden","combat transition blocks changing selection");
combatStart=0;origin=false;
check(!A.chooseToadBanner("front").ok&&savedFlags.afeix_banner_style=="golden"&&assets.getBanner()=="banner_15","other origin cannot change banner");
origin=true;A.set("banner_style","retired-style");
A.syncToadBanner();
check(A.toadBanner().key=="native"&&sprites.banner.brush=="banner_15","unknown saved style falls back to founding choice");
local flags=::World.Flags;::World.Flags=null;
check(A.toadBanner().key=="native","pre-campaign banner lookup does not require flags");
::World.Flags=flags;
foreach (variant in [1,4,15,21]) {
    local number=variant<10?"0"+variant:variant.tostring();
    assets.m.Banner="banner_"+number;assets.m.BannerID=variant;
    check(A.chooseToadBanner("golden").ok&&A.chooseToadBanner("native").ok,"native/custom round trip "+number);
    check(assets.m.Banner=="banner_"+number&&assets.m.BannerID==variant&&sprites.banner.brush=="banner_"+number,"founding settings never overwritten "+number);
    check(parts.background.brush=="player_banner_"+number&&spare.m.IconLarge=="weapons/banner/banner_"+number+".png","weapon variant cannot override founding choice "+number);
    sprites.banner.brush="before-load";world.onDeserialize(null);
    check(savedFlags.afeix_banner_style=="native"&&sprites.banner.brush=="banner_"+number&&parts.background.brush=="player_banner_"+number,"native selection remains restored after load "+number);
}
print("TESTS_PASSED="+checks+"\n");
