"""Generate stable personal backgrounds inheriting each existing native template."""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def build_backgrounds():
    records = json.loads((ROOT / 'data/character-backgrounds.json').read_text(encoding='utf-8'))
    source = (ROOT / 'src/scripts/mods/afeix/characters.nut').read_text(encoding='utf-8-sig')
    order = json.loads(re.search(r'A\.CharacterOrder <- (\[[^\n]+\]);', source)[1])
    if [row['key'] for row in records] != order:
        raise ValueError('Background identities must match the current roster')
    blocks = dict(re.findall(r'^    ([a-z0-9_]+) = \{(.*?)^    \}', source, re.M | re.S))
    quote = lambda value: json.dumps(value, ensure_ascii=False)
    definitions = ['// Generated by tools/build_backgrounds.py from data/character-backgrounds.json.',
                   '::AfeixExpedition.CharacterBackgrounds <- {']
    folder = ROOT / 'src/scripts/skills/backgrounds'
    folder.mkdir(parents=True, exist_ok=True)
    for row in records:
        key = row['key']
        native = re.search(r'background = "([a-z_]+)"', blocks[key])[1]
        definitions.append(f'    {key} = {{ name = {quote(row["name"])}, description = {quote(row["description"])} }},')
        script = f'''// Generated; retain native attributes, event eligibility and save layout.
this.afeix_{key}_background <- this.inherit("scripts/skills/backgrounds/{native}", {{
    m = {{}},
    function create() {{
        this.{native}.create();
        this.m.ID = "background.afeix_{key}";
        ::AfeixExpedition.configureCharacterBackground(this, "{key}");
    }},
    function buildDescription(final = false) {{
        ::AfeixExpedition.configureCharacterBackground(this, "{key}");
    }},
    function onBuildDescription() {{ return this.m.RawDescription; }}
}});
'''
        (folder / f'afeix_{key}_background.nut').write_text(script, encoding='utf-8')
    definitions.append('};')
    (ROOT / 'src/scripts/mods/afeix/background_data.nut').write_text('\n'.join(definitions) + '\n', encoding='utf-8')
    return len(records)


if __name__ == '__main__':
    print(f'Built {build_backgrounds()} personal backgrounds.')
