"""Compile the two personal story chains and publish their readable script."""
import json
from pathlib import Path
from render_skill_expansion import nut

ROOT = Path(__file__).resolve().parents[1]

def build():
    data = json.loads((ROOT / 'data/blue-team-stories.json').read_text(encoding='utf-8'))
    assert data['schema'] == 1 and data['order'] == list(data['scenes'])
    assert len(data['order']) == 4 and set(data['epilogues']) == {'xiaohani', 'yanzi'}
    for key, scene in data['scenes'].items():
        assert scene['owner'] in data['epilogues'] and scene['place'] in {'safe', 'town'}
        assert len(scene['choices']) == len(scene['outcomes']) == 2
        assert scene['level'] >= 3 and scene['battles'] >= 3
        if scene['previous']:
            assert data['order'].index(scene['previous']) < data['order'].index(key)
            assert data['scenes'][scene['previous']]['owner'] == scene['owner']
            assert len(scene['priorText']) == 2 and scene['winsAfterPrevious'] >= 1
    for key, ending in data['epilogues'].items():
        assert data['scenes'][ending['final']]['owner'] == key and len(ending['choices']) == 2
        assert all(set(option) == {'good', 'lean'} for option in ending['choices'])
    text = '// Generated by tools/build_blue_team_stories.py.\nlocal A=::AfeixExpedition;\n'
    for field, source in [('BlueStoryOrder', 'order'), ('BlueStories', 'scenes'), ('BlueEpilogues', 'epilogues')]:
        text += 'A.' + field + ' <- ' + nut(data[source]) + ';\n'
    text += 'foreach(k,d in A.BlueStories) A.Chronicles[k] <- d;\n'
    (ROOT / 'src/scripts/mods/afeix/blue_story_data.nut').write_text(text, encoding='utf-8')
    lines = ['# 罗一可与眼子｜完整个人剧情', '', '更新：2026-09-28。' + data['scope'], '',
             '两人各有招募相遇、3 级个人成长、两段后续与对应退隐结局。后续使用现有旅途事件入口；黑旗名册中的“旅途旧事”只展示已经经历的段落。', '',
             '首段：本人存活在队，已完成个人成长，至少 4 级、亲自参战 5 次。第二段：至少 7 级、亲自参战 8 次，首段之后战团再获胜 2 次且间隔至少 2 天。每段结算一次，选择持久保存；两人的选择各自独立。', '',
             '阿飞与本人都须存活在队；安全地点交谈，标为城镇的事件还需靠近友好城镇。每个选项只让当事人心情 +0.25，不扣团款、不凭空生成物资，也不让人物直接离队。', '',
             '[人物介绍与招募](character-stories.md) · [成长数据](../../data/member-growth.json) · [头像与装备预览](../../build/blue-team-stories/portraits-review.png)', '']
    for key in data['order']:
        scene = data['scenes'][key]
        lines += ['## ' + scene['title'], '', '地点：' + ('友好城镇附近' if scene['place'] == 'town' else '安全营地或友好城镇附近') + '。', '', scene['text'], '']
        if scene.get('priorText'):
            lines += ['### 前次选择的回应', '']
            for i, value in enumerate(scene['priorText'], 1): lines += [f'前段选项 {i}：{value}', '']
        for i, (choice, outcome) in enumerate(zip(scene['choices'], scene['outcomes']), 1):
            lines += [f'### 选项 {i}：{choice}', '', outcome, '']
    for key, ending in data['epilogues'].items():
        lines += ['## ' + ('罗一可' if key == 'xiaohani' else '眼子') + '的选择结局', '',
                  '仅在对应终段已经完成、本人存活在队且战团退隐时使用；未完成剧情、离队、阵亡与战团败亡仍按各自实际状态收尾。', '']
        for i, choice in enumerate(ending['choices'], 1):
            lines += [f'### 终段选项 {i}', '', '**声名已立**：' + choice['good'], '', '**平凡收旗**：' + choice['lean'], '']
    (ROOT / 'docs/design/blue-team-stories.md').write_text('\n'.join(lines), encoding='utf-8')
    return len(data['order'])

if __name__ == '__main__': print(f'BLUE_TEAM_STORIES={build()}')
