"""Compile the approved workbook-checked V2 proposal; never refresh its baseline."""
import hashlib
import json
from pathlib import Path
from zipfile import ZipFile
from audit_balance_v2_refresh import values
from render_skill_expansion import nut

ROOT = Path(__file__).resolve().parents[1]
DESIGN = ROOT / 'docs/design/balance-v2'


def render():
    proposal = json.loads((DESIGN / 'proposal.json').read_text(encoding='utf-8'))
    traits = json.loads((DESIGN / 'trait-design.json').read_text(encoding='utf-8'))['definitions']
    workbook = DESIGN / '全人物数值与招募总表.xlsx'
    with ZipFile(workbook) as z:
        recruit, attrs, skills = (values(z, n) for n in (2, 3, 6))
        fixed_traits, equipment, events = (values(z, n) for n in (16, 5, 7))
        for index, person in enumerate(proposal['people']):
            row = index + 6
            assert recruit[f'B{row}'][1] == person['key']
            assert fixed_traits[f'Q{row}'][1] == person['level_bonus_per_level'][1], (person['key'], 'level stamina')
            for col, field in zip('EFGHIJMNO', ['day','battles','contracts','towns','highest_level','join_level','service_fee','wage','equipment_value']):
                assert recruit[f'{col}{row}'][1] == person[field], (person['key'], field)
            for offset, field in enumerate(proposal['fields']):
                r = 6 + index * 8 + offset
                assert attrs[f'D{r}'][1] == person['attrs'][offset]
                assert attrs[f'E{r}'][1] == person['stars'].get(field, 0)
                assert attrs[f'F{r}'][1] == person['allocation'][offset]
                for col, choice in [('G', 0), ('H', 1)]:
                    assert attrs[f'{col}{r}'][1] == person['growth_choices'][choice]['bonuses'].get(field, 0)
            for col, field in [('C','equipment'),('D','bag')]:
                expected = '、'.join(proposal['items'][k]['name'] for k in person[field]) or '无'
                assert (equipment[f'{col}{row}'][1] or '无') == expected, (person['key'], field, expected)
            for col, field in [('E','body_armor'),('F','head_armor'),('G','equipment_fatigue'),('H','bag_fatigue'),('J','equipment_value')]:
                assert equipment[f'{col}{row}'][1] == person[field]
            for col, trait in zip('CD',person['fixed_traits']):
                assert fixed_traits[f'{col}{row}'][1] == traits[trait]['name']
        for index, skill in enumerate(proposal['skills']):
            r = index + 6
            assert skills[f'M{r}'][1] == skill['key']
            for col, field in [('D','ap'),('E','fatigue'),('F','cd'),('G','range')]:
                assert skills[f'{col}{r}'][1] == skill[field], (skill['key'], field)
            for col, field in [('I','text'),('J','mastery')]:
                assert skills[f'{col}{r}'][1] == skill[field], (skill['key'], field)
            assert skills[f'H{r}'][1] == skill.get('mastery_fatigue',skill['fatigue'])
        for row, route in enumerate(proposal['routes'], 6):
            for col, field in [('A','name'),('B','passive'),('C','ap'),('D','fatigue'),('E','cd'),('F','effect'),('G','economy')]:
                assert events[f'{col}{row}'][1] == route[field]
            assert events[f'H{row}'][1] == proposal['route_unlock']
        assert values(z, 15)['B21'][1] == proposal['assumptions']['heavy_fatigue_buffer']
    people = {}
    for p in proposal['people']:
        people[p['key']] = {k: p[k] for k in ['attrs','stars','wage','equipment','bag','fixed_traits','runtime_base_before_traits','day','battles','contracts','towns','highest_level','join_level','service_fee','equipment_value','suggested_price']}
        people[p['key']]['old_attrs'] = p['current']['attrs']
        people[p['key']]['level_bonus_per_level'] = p['level_bonus_per_level']
        people[p['key']]['old_hire_cost'] = p['current']['hireCost']
    definitions = {}
    for s in proposal['skills']:
        definitions[s['key']] = {k:v for k,v in s.items() if k not in ['current_text','owner_name','change','v1']}
        if s['key'].startswith(('yanzi_', 'xiwen_')):
            definitions[s['key']]['extended'] = True
            definitions[s['key']]['growth'] = s['key'].endswith(('_reply','_travel'))
            definitions[s['key']]['mode'] = 'buff'
            definitions[s['key']]['once'] = False
            definitions[s['key']]['shield'] = False
            definitions[s['key']]['target'] = 'ally' if s['key'].endswith('_cover') else 'self'
            if s['key'].endswith('_cover'): definitions[s['key']]['shield'] = True
    payload = {'people': people, 'traits': {k:{'id':v['id'], 'path':v['native_path'].removesuffix('.cnut'), 'delta':v['delta'], 'excluded':v['excluded']} for k,v in traits.items()}, 'skills': definitions, 'routes':{r['id']:r for r in proposal['routes']}}
    target = ROOT / 'src/scripts/mods/afeix/balance_v26_data.nut'
    target.write_text('// Generated by tools/render_balance_v26.py from the approved V2 workbook.\n::AfeixExpedition.BalanceV26 <- ' + nut(payload) + ';\n', encoding='utf-8')
    report = {'workbook_sha256':hashlib.sha256(workbook.read_bytes()).hexdigest(), 'people':len(people), 'skills':len(definitions), 'runtime_data_sha256':hashlib.sha256(target.read_bytes()).hexdigest()}
    (ROOT / 'build/balance-v26-source.json').write_text(json.dumps(report,indent=2)+'\n', encoding='utf-8')
    return report


if __name__ == '__main__':
    print(json.dumps(render()))
