"""Compile the reviewed skill data into Squirrel, with no runtime JSON dependency."""
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]

def nut(value):
    if isinstance(value, dict):
        return '{' + ','.join('['+json.dumps(k,ensure_ascii=False)+']='+nut(v) for k,v in value.items()) + '}'
    if isinstance(value, list):
        return '['+','.join(map(nut,value))+']'
    return json.dumps(value,ensure_ascii=False)

def render():
    data=json.loads((ROOT/'data/member-skill-expansion.json').read_text(encoding='utf-8'))
    assert len(data['groups'])==33 and all(len(v)==3 for v in data['groups'].values())
    assert len({k for v in data['groups'].values() for k in v})==99
    assert len(data['skills'])==81
    for k,d in data['skills'].items():
        assert k in data['groups'][d['owner']]
        assert d['growth']==(data['groups'][d['owner']].index(k)==2)
        if d['active']: assert d['ap']>0 and d['fatigue']>=0 and d['mode'] in ['buff','team','mark','weapon','step','swap','cover','taunt','unnet','snare']
    text='// Generated by tools/render_skill_expansion.py. Edit data/member-skill-expansion.json.\nlocal A=::AfeixExpedition;\n'
    text+='foreach(k,v in '+nut(data['groups'])+') A.MemberSkills[k] <- v;\n'
    text+='foreach(k,v in '+nut(data['skills'])+') A.MemberSkillDefs[k] <- v;\n'
    text+='A.CatalogEffects <- '+nut(data['effects'])+';\n'
    (ROOT/'src/scripts/mods/afeix/member_catalog_data.nut').write_text(text,encoding='utf-8')
    return data

if __name__=='__main__': render()
